import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CategoryProvider } from "@/context/category-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CategoryProvider>
          <div>{children}</div>
        </CategoryProvider>
      </body>
    </html>
  );
}
